### ISSUE TITLE
rename the repo to EMPHYSIS.github.io

### ISSUE THREAD

**Issue by thorade** [EMPHYSIS/EMPHYSIS.github.io#1]
Just a very minor suggestion: Rename the repository to EMPHYSIS.github.io
https://help.github.com/articles/user-organization-and-project-pages/

The URL of the homepage would then change from 
https://emphysis.github.io/web/  to
https://emphysis.github.io/

**Comment by olivleno** [comment]
Thanks for the advise. I renamed the repository but unfortunately the web address did not change.
Is there anything I can do to enforce it?

**Comment by olivleno** [comment]
Thanks for the advise. I tried as you said but the web address did not change. Is there anything else I should try?

**Comment by olivleno** [comment]
Thanks for the hint.
